# Generated by Django 3.2 on 2021-05-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contacto',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
